name: PortalsPE
main: PortalsPE\Main
api: 2.0.0
author: luca28pet
description: A portals plugin
commands:
  portal:
    description: Main PortalsPE commmand
    usage: /portal pos1|pos2|create|list
    permission: portal.admin
permission:
  portal.admin:
    description: admin command
    default: op